INSERT INTO PROFESORADO (Codigo, Nombre, Apellidos, DNI, Especialidad, Fecha_Nac, Antiguedad) 
    VALUES (2, 'MARIA LUISA', 'FABRE BERDUN', '51083099F', 'TECNOLOGIA', '3/31/1975', 4); 
 
INSERT INTO PROFESORADO (Codigo, Nombre, Apellidos, Especialidad, Fecha_Nac, Antiguedad) 
    VALUES (3, 'JAVIER', 'JIMENEZ HERNANDO', 'LENGUA', '5/4/1969', 10); 
 
INSERT INTO PROFESORADO (Codigo, Nombre, Apellidos, DNI, Especialidad, Fecha_Nac, Antiguedad)
    VALUES (4, 'ESTEFANIA', 'FERNANDEZ MARTINEZ', '19964324W', 'INGLES', '6/22/1973', 5); 
 
INSERT INTO PROFESORADO (Codigo, Nombre, Apellidos) VALUES (5, 'JOSE M.', 'ANERO PAYAN');

UPDATE PROFESORADO SET ESPECIALIDAD = 'Informática', DNI = '9876543C' WHERE CODIGO = 3; 

UPDATE PROFESORADO SET ANTIGUEDAD = ANTIGUEDAD + 2 WHERE ANTIGUEDAD > 2;

DELETE ALUMNADO WHERE COD_CURSO = 2 AND SEXO = 'H';

INSERT INTO ALUMNADO (NOMBRE, APELLIDOS, SEXO, FECHA_NAC) SELECT Nombre, Apellidos, Sexo, Fecha_Nac FROM ALUMNADO_NUEVO;

UPDATE CURSOS SET MAX_ALUMN = (SELECT COUNT(*) FROM ALUMNADO WHERE COD_CURSO = 1) WHERE CODIGO = 1; 
 
DELETE FROM ALUMNADO WHERE COD_CURSO IN (SELECT CODIGO FROM CURSOS WHERE COD_PROFE = 3); 