-- Modificaciones
--A)
ALTER TABLE STOCK ADD(
    FechaUltimaEntrada DATE DEFAULT SYSDATE,
    Beneficio NUMBER(2) CHECK (Beneficio IN (1,2,3,4,5))
);

ALTER TABLE PRODUCTO DROP COLUMN Descripcion;
ALTER TABLE PRODUCTO ADD(
    perecedero VARCHAR2(2) CHECK (perecedero IN ('S', 'N'))
);
ALTER TABLE PRODUCTO MODIFY Denoproducto VARCHAR2(50);

ALTER TABLE FAMILIA ADD(
    IVA NUMBER(4) CHECK (IVA IN (21, 10, 4))
);

ALTER TABLE TIENDA MODIFY CodigoPostal UNIQUE;

--B)
RENAME STOCK TO PRODXTIENDAS;
--C)
-- anttes de borrar tabla FAMILIA borro columna Codfamilia por que es Clave ajena que referencia a Codfamilia de la tabla FAMILIA
ALTER TABLE PRODUCTO DROP COLUMN Codfamilia;
DROP TABLE FAMILIA;

CREATE USER C##INVITADO IDENTIFIED BY INVITADO DEFAULT TABLESPACE USERS;

GRANT ALTER, SELECT, INSERT, UPDATE, DELETE ON PRODUCTO TO C##INVITADO;

REVOKE ALTER, DELETE ON PRODUCTO FROM C##INVITADO;

